{"uuid":"28872484-a6e3-4c0f-8b9b-b45c5f500965","historyId":"d9c33f9dd65deaf5301d616b38c91f0c","fullName":"Login.LoginHataliParolaTest.LoginHataliParola","labels":[{"name":"package","value":"Login.LoginHataliParolaTest"},{"name":"testClass","value":"Login.LoginHataliParolaTest"},{"name":"testMethod","value":"LoginHataliParola"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"ttPay_POM"},{"name":"subSuite","value":"Login.LoginHataliParolaTest"},{"name":"host","value":"Ugur-MacBook-Pro.local"},{"name":"thread","value":"429@Ugur-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"minor"}],"links":[],"name":"LoginHataliParola","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [5640801281] but found [Girdiğin cep telefonu veya parola bilgisi hatalı. Lütfen bilgilerini kontrol ederek tekrar dene.]","trace":"java.lang.AssertionError: expected [5640801281] but found [Girdiğin cep telefonu veya parola bilgisi hatalı. Lütfen bilgilerini kontrol ederek tekrar dene.]\n\tat org.testng.Assert.fail(Assert.java:99)\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\n\tat org.testng.Assert.assertEquals(Assert.java:122)\n\tat org.testng.Assert.assertEquals(Assert.java:629)\n\tat org.testng.Assert.assertEquals(Assert.java:639)\n\tat Libraries.TestUtils.testAssertFunctions(TestUtils.java:97)\n\tat Login.LoginHataliParolaTest.LoginHataliParola(LoginHataliParolaTest.java:34)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\n\tat org.testng.TestRunner.run(TestRunner.java:596)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\n\tat org.testng.TestNG.run(TestNG.java:1031)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\n"},"stage":"finished","description":"Kullancı Adı ve Yanlış Şifre ile giriş yapma senaryosu.","steps":[],"attachments":[{"name":"Screenshot","source":"d82ef767-17be-4f66-b41c-df11fa925c39-attachment"}],"parameters":[],"start":1668793297483,"stop":1668793302016}